name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '17'
    - name: Setup Clojure tools
      uses: DeLaGuardo/setup-clojure@13.6.1
      with:
        lein: latest
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Build JAR
      run: lein uberjar
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7
      with:
        name: Standalone JAR
        path: target/*-standalone.jar
